sudo: false
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
    - PACKAGE=shairport-sync
  matrix:
    - SDK_URL=https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/snapshots/trunk/kirkwood/generic/OpenWrt-SDK-kirkwood-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/snapshots/trunk/lantiq/generic/OpenWrt-SDK-lantiq-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/snapshots/trunk/ramips/generic/OpenWrt-SDK-ramips-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://us.archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.1.6-1_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- tar xjf $FILE
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/files package/$PACKAGE/
- ./scripts/feeds update -a
- ./scripts/feeds install alsa-lib libdaemon libpopt alsa-utils 
script:
- export STAGING_DIR=$(readlink -e $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/staging_dir/toolchain-*/bin)
- export HOST=$(readlink -e $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/staging_dir/host/bin)
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$HOST:$STAGING_DIR:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- make V=s
- find $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/bin/
- find . -name *.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
deploy:
  provider: releases
  api_key:
    secure: SSX0JBJmJFT4Q+ZYCHFwQDCqNgQoVxmRhUdRmhiAaSjz4SQf7ewNhTB2ap14Mh75rhaHd4+VNSx3sFiFmQsFwXMK1FbkaS4b5GTbPTGsbXdRKJDXJqvgdZVsruAt5hL7I5Sda4CllN3ZOhEUNmc1DsafjLFWVHDnt6CZdHA2eME=
  skip_cleanup: true
  file_glob: true
  file: $TRAVIS_BUILD_DIR/$PACKAGE*.ipk
  on:
    tags: true
    all_branches: true
