sudo: false
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
    - PACKAGE=shairport-sync
  matrix:
    - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/ar71xx/generic/OpenWrt-SDK-15.05-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/kirkwood/generic/OpenWrt-SDK-15.05-kirkwood_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2
    - SDK_URL=httpshttps://downloads.openwrt.org/chaos_calmer/15.05/lantiq/xway/OpenWrt-SDK-15.05-lantiq-xway_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/ramips/rt305x/OpenWrt-SDK-15.05-ramips-rt305x_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://us.archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.1.6-1_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- tar xjf $FILE
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/files package/$PACKAGE/
- ./scripts/feeds update -a
- ./scripts/feeds install alsa-lib libdaemon libpopt alsa-utils 
script:
- export STAGING_DIR=$(readlink -e $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/staging_dir/toolchain-*/bin)
- export HOST=$(readlink -e $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/staging_dir/host/bin)
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$HOST:$STAGING_DIR:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- make V=s
- find $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/bin/
- find . -name *.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
before_deploy:
  git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: SSX0JBJmJFT4Q+ZYCHFwQDCqNgQoVxmRhUdRmhiAaSjz4SQf7ewNhTB2ap14Mh75rhaHd4+VNSx3sFiFmQsFwXMK1FbkaS4b5GTbPTGsbXdRKJDXJqvgdZVsruAt5hL7I5Sda4CllN3ZOhEUNmc1DsafjLFWVHDnt6CZdHA2eME=
  skip_cleanup: true
  file_glob: true
  file: $TRAVIS_BUILD_DIR/*.ipk
  on:
    tags: true
    all_branches: true
