language: c
sudo: false
dist: trusty

env:
  matrix:
    - SDK_URL=http://mirror1.mirror.garr.it/mirrors/openwrt/barrier_breaker/14.07/ar71xx/generic/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
    - SDK_URL=http://mirror1.mirror.garr.it/mirrors/openwrt/barrier_breaker/14.07/kirkwood/generic/OpenWrt-SDK-kirkwood-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
    - SDK_URL=http://mirror1.mirror.garr.it/mirrors/openwrt/barrier_breaker/14.07/lantiq/xway/OpenWrt-SDK-lantiq-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
    - SDK_URL=http://mirror1.mirror.garr.it/mirrors/openwrt/barrier_breaker/14.07/ramips/rt305x/OpenWrt-SDK-ramips-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
install:
 - mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
 - wget -c $SDK_URL
 - mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
 - export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
 - file $FILE
 - tar xjf $FILE
 - cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
 - ./scripts/feeds update -a
 - ./scripts/feeds install libavahi alsa-lib libdaemon libpopt
 - cd package
 - git clone --branch=barrier-breaker https://github.com/mikebrady/shairport-sync-for-openwrt.git
 - git clone https://github.com/mikebrady/libsoxr-for-openwrt.git
 - cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*

script:
 - make V=s
 - find $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/bin/
 - find . -name *.ipk -exec cp {} $TRAVIS_BUILD_DIR \;

addons:
  apt:
    packages:
    - libssl-dev
    - libncurses5-dev
    - unzip
    - subversion
    - zlib1g-dev
    - gawk
    - gcc-multilib
    - flex
    - gettext
    - libxml-parser-perl

before_deploy:
  git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: SSX0JBJmJFT4Q+ZYCHFwQDCqNgQoVxmRhUdRmhiAaSjz4SQf7ewNhTB2ap14Mh75rhaHd4+VNSx3sFiFmQsFwXMK1FbkaS4b5GTbPTGsbXdRKJDXJqvgdZVsruAt5hL7I5Sda4CllN3ZOhEUNmc1DsafjLFWVHDnt6CZdHA2eME=
  skip_cleanup: true
  file_glob: true
  file: $TRAVIS_BUILD_DIR/*.ipk
  on:
    tags: true
    all_branches: true
